import { EmployeesTable } from "../../components/admin/employees-table";
const mockEmployees = [
  {
    id: 1,
    fullname: "Amelia Johnson",
    email: "amelia.johnson@example.com",
    role: "admin",
    status: "Active",
    lastActive: "2h ago",
  },
  {
    id: 2,
    fullname: "Daniel Kim",
    email: "daniel.kim@example.com",
    role: "editor",
    status: "Active",
    lastActive: "1d ago",
  },
  {
    id: 3,
    fullname: "Sofia Martinez",
    email: "sofia.martinez@example.com",
    role: "viewer",
    status: "Invited",
    lastActive: undefined,
  },
  {
    id: 4,
    fullname: "Liam Brown",
    email: "liam.brown@example.com",
    role: "editor",
    status: "Suspended",
    lastActive: "3mo ago",
  },
  {
    id: 5,
    fullname: "Noah Wilson",
    email: "noah.wilson@example.com",
    role: "manager",
    status: "Active",
    lastActive: "5m ago",
  },
  {
    id: 6,
    fullname: "Olivia Davis",
    email: "olivia.davis@example.com",
    role: "designer",
    status: "Active",
    lastActive: "4h ago",
  },
  {
    id: 7,
    fullname: "Ethan Clark",
    email: "ethan.clark@example.com",
    role: "devops",
    status: "Active",
    lastActive: "30m ago",
  },
  {
    id: 8,
    fullname: "Isabella Garcia",
    email: "isabella.garcia@example.com",
    role: "hr",
    status: "Active",
    lastActive: "2d ago",
  },
  {
    id: 9,
    fullname: "Mason Lee",
    email: "mason.lee@example.com",
    role: "qa",
    status: "Active",
    lastActive: "1w ago",
  },
  {
    id: 10,
    fullname: "Mia Thompson",
    email: "mia.thompson@example.com",
    role: "viewer",
    status: "Invited",
    lastActive: undefined,
  },
  {
    id: 11,
    fullname: "Aiden Walker",
    email: "aiden.walker@example.com",
    role: "editor",
    status: "Active",
    lastActive: "3h ago",
  },
  {
    id: 12,
    fullname: "Harper Hall",
    email: "harper.hall@example.com",
    role: "designer",
    status: "Active",
    lastActive: "6h ago",
  },
  {
    id: 13,
    fullname: "Lucas Young",
    email: "lucas.young@example.com",
    role: "dev",
    status: "Active",
    lastActive: "10m ago",
  },
  {
    id: 14,
    fullname: "Evelyn Hernandez",
    email: "evelyn.hernandez@example.com",
    role: "admin",
    status: "Active",
    lastActive: "1h ago",
  },
  {
    id: 15,
    fullname: "Benjamin King",
    email: "benjamin.king@example.com",
    role: "dev",
    status: "Active",
    lastActive: "8h ago",
  },
  {
    id: 16,
    fullname: "Abigail Wright",
    email: "abigail.wright@example.com",
    role: "hr",
    status: "Suspended",
    lastActive: "2mo ago",
  },
  {
    id: 17,
    fullname: "Logan Scott",
    email: "logan.scott@example.com",
    role: "qa",
    status: "Active",
    lastActive: "4d ago",
  },
  {
    id: 18,
    fullname: "Charlotte Green",
    email: "charlotte.green@example.com",
    role: "manager",
    status: "Active",
    lastActive: "12h ago",
  },
  {
    id: 19,
    fullname: "Henry Adams",
    email: "henry.adams@example.com",
    role: "editor",
    status: "Active",
    lastActive: "2w ago",
  },
  {
    id: 20,
    fullname: "Amelia Parker",
    email: "amelia.parker@example.com",
    role: "viewer",
    status: "Invited",
    lastActive: undefined,
  },
  {
    id: 21,
    fullname: "Owen Rivera",
    email: "owen.rivera@example.com",
    role: "devops",
    status: "Active",
    lastActive: "7m ago",
  },
  {
    id: 22,
    fullname: "Zoe Cooper",
    email: "zoe.cooper@example.com",
    role: "designer",
    status: "Active",
    lastActive: "9h ago",
  },
  {
    id: 23,
    fullname: "Jack Ramirez",
    email: "jack.ramirez@example.com",
    role: "dev",
    status: "Active",
    lastActive: "3d ago",
  },
  {
    id: 24,
    fullname: "Luna Brooks",
    email: "luna.brooks@example.com",
    role: "viewer",
    status: "Active",
    lastActive: "1mo ago",
  },
  {
    id: 25,
    fullname: "Wyatt Sanders",
    email: "wyatt.sanders@example.com",
    role: "editor",
    status: "Active",
    lastActive: "18h ago",
  },
  {
    id: 26,
    fullname: "Aria Price",
    email: "aria.price@example.com",
    role: "hr",
    status: "Invited",
    lastActive: undefined,
  },
  {
    id: 27,
    fullname: "Samuel Bennett",
    email: "samuel.bennett@example.com",
    role: "manager",
    status: "Active",
    lastActive: "2d ago",
  },
  {
    id: 28,
    fullname: "Ella Cox",
    email: "ella.cox@example.com",
    role: "qa",
    status: "Active",
    lastActive: "5d ago",
  },
  {
    id: 29,
    fullname: "Caleb Foster",
    email: "caleb.foster@example.com",
    role: "dev",
    status: "Suspended",
    lastActive: "5mo ago",
  },
  {
    id: 30,
    fullname: "Nora Reed",
    email: "nora.reed@example.com",
    role: "admin",
    status: "Active",
    lastActive: "20m ago",
  },
];

export default function EmployeesPage() {
  return (
    <>
      <h1 className="mb-4 text-2xl font-bold">Employees</h1>
      <EmployeesTable data={mockEmployees} />
    </>
  );
}
